apiVersion: v1
kind: Service
metadata:
  name: platformsService-srv
  labels:
    app: platformservice
spec:
  type: NodePort
  selector:
       app: platformservice
  ports:
         - name: platformservice
           protocol: TCP
           Port: 80
           targetPort: 80